import img1 from "./images/img1.jpg";
import img2 from "./images/img2.jpg";
import img3 from "./images/img3.jpg";
import img4 from "./images/img4.jpg";
import img5 from "./images/img5.jpg";
import img6 from "./images/img6.jpg";
import img7 from "./images/img7.jpg";
import img8 from "./images/img8.jpg";
import img9 from "./images/img9.jpg";




export const HORRORS = [
    {
        BookID: 1,
        BName: "Killer",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img1,
        stock: 25,
    },
    {
        BookID: 2,
        BName: "Killer",
        Author: "Suzanne Collins",
        AgeRate: "12",
        DatePub: "2009-01-12",
        Description: "The beginnig of a collection in the life of a dystopic society.The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love. ",
        Genre: "Young Adult, Fiction, Dystopia, Romance",
        price: 9.99,
        imageUri: img2,
        stock: 10,
    },
    {
        BookID: 3,
        BName: "Killer",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img3,
        stock: 25,
    },
    {
        BookID: 4,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img4,
        stock: 25,
    },
    {
        BookID: 5,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img5,
        stock: 25,

    },
    {
        BookID: 6,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img6,
        stock: 25,
    },
    {
        BookID: 7,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img7,
        stock: 25,
    },
    {
        BookID: 8,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img8,
        stock: 25,
    },
    {
        BookID: 9,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img9,
        stock: 25,
    },
    {
        BookID: 10,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img9,
        stock: 25,
    },
    {
        BookID: 11,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img9,
        stock: 25,
    },
    {
        BookID: 8,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img9,
        stock: 25,
    },
    {
        BookID: 8,
        BName: "Metamorphis",
        Author: "Franz Kafka",
        AgeRate: "12",
        DatePub: "2002-10-10",
        Description: "One of Kafka's best selling novels and a seemignly bizarre masterpiece.It is the story of a young man who, transformed overnight into a giant beetle-like insect, becomes an object of disgrace to his family, an outsider in his own home, a quintessentially alienated man. A harrowing—though absurdly comic—meditation on human feelings of inadequacy, guilt, and isolation, The Metamorphosis has taken its place as one of the most widely read and influential works of twentieth-century fiction. ",
        Genre: "fiction, fantasy, philosophy",
        price: 8.99,
        imageUri: img9,
        stock: 25,
    },
];